### ISSUE TITLE
Dispatch runLoop deadlock when removing a handler from within a handler

### ISSUE THREAD

**Issue by Santiclause** [fluffle/goirc#102]
Spent a while tracking down what was going on - when you try to call a returned `Remover`'s `Remove` method from within an event handler, it deadlocks because dispatch holds a read lock until it finishes dispatching.

**Comment by iopred** [comment]
Ah ty, will figure out a solution here.

**Comment by fluffle** [comment]
Sorry about that. Not the first bug caused by over-broad locking. Please can you see if c981f8f fixes your problem? I think it ought to.
