### ISSUE TITLE
Client gets very confused when nickname is longer than NICKLEN

### ISSUE THREAD

**Issue by shammash** [fluffle/goirc#110]
When a client is created with a nickname longer than the server's 005 NICKLEN, it does not understand that its username will be truncated by the server. This breaks any further nick-related operation because h_NICK() and h_433() do not recognize the truncated username.

The client should probably become aware of at least some 005 parameters, as suggested in https://github.com/fluffle/goirc/blob/f0ae9bb5090ad5d874aa4d47fe0abc5696fa2f60/client/handlers.go#L62

**Comment by fluffle** [comment]
Very sneaky filing bugs before the global day off :-p

**Comment by fluffle** [comment]
The bug is actually in h_001, which should accept the server-side view of what the client nick is. I agree that 005 handling would be nice, though :-)

**Comment by shammash** [comment]
Thank you for looking into this straight away!
I'm doing my best to make sure people do not get bored during this endless lockdown ;)
