### ISSUE TITLE
xdcc client

### ISSUE THREAD

**Issue by ostafen** [fluffle/goirc#113]
Hi, first of all, thank you for the library. I'm not sure if this is the right place for this.
I wrote an xdcc command line tool (based on this package) which allows to search and retrieve irc files in a user friendly way:
https://github.com/ostafen/xdcc-cli

I would appreciate if you could add a link to my client in a section reporting all the projects related to your IRC package.
Thank you in advance

**Comment by fluffle** [comment]
Send me a PR and I'll merge it :-)

**Comment by ostafen** [comment]
Thank you for your answer. The PR is available for review :-)

**Comment by fluffle** [comment]
Sorry for the delay and thanks for the PR. I don't have much spare time for this any more :-)
