### ISSUE TITLE
Invalid/expired certificate

### ISSUE THREAD

**Issue by ZG92cnlkCg** [fluffle/goirc#114]
When trying to connect to an IRC server with SSL, I get the following error:

```Connection error x509: certificate has expired or is not yet valid: current time 2022-02-02T23:01:43-05:00 is after 2022-02-01T07:44:35Z```

I suspect the issue might be with the library? I compiled my program, which uses goirc, on two, different operating systems, and I still get the error.

Any guidance would be appreciated.

**Comment by fluffle** [comment]
Heyoo. I think the error is clear enough -- your cert expired on 1st February. You can fix this by renewing it with an expiry time that is in the future.

This validation is done by crypto/tls, not goirc. If you would like to stop this from happening (and render your connections susceptible to MitM attacks) you can supply a non-default *tls.Config with InsecureSkipVerify set to true in the IRC connections Config.SSLConfig field.

**Comment by ZG92cnlkCg** [comment]
Thanks. Do you know which certificate crypto/tls is likely complaining about?

**Comment by fluffle** [comment]
The certificate the IRC server presents to your client as part of the SSL handshake. 

Sorry, me saying "your cert" was a bit misleading -- I run an IRCd for a small network too so I'm used to managing my own server certs. You're probably not running the server! Having said that, I would also expect most public IRC networks to maintain valid certs, so it is a little odd you're encountering this. What network are you connecting to, out of interest?

**Comment by ZG92cnlkCg** [comment]
I'm encountering this when connecting to a private server. So, you're saying this cert issue could be from the server side?

**Comment by fluffle** [comment]
Yes, the cert issue is because the server's SSL cert has expired.

https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_Handshake has some more details about what exactly is sent between the client and the server as the TLS negotiation takes place. If you want to manually inspect the cert you can use `openssl(1)` to connect to the server:

 ```
openssl s_client -connect irc.your-network.net:6697 -debug -showcerts 
```

You can find the certs between the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` lines. Dump that into a file named `server.pem` and you can inspect it like this:

```
openssl x509 -in server.pem -noout -text
```

Hope this helps!

**Comment by ZG92cnlkCg** [comment]
Yes, that helps. Thank you so much!

**Comment by tanis2000** [comment]
@fluffle would it be possible to skip server certificate verification when connecting to a server with expired certiifcates?

**Comment by fluffle** [comment]
It is possible, yes. You can provide your own [`*tls.Config`](https://pkg.go.dev/crypto/tls@go1.22.4#Config) in the client's `SSLConfig` field of the `Config` struct. If you set `InsecureSkipVerify` to `true` in that `*tls.Config` then the TLS layer will no longer try to validate the server's certs on connect.
