### ISSUE TITLE
Update (*Line) Public to accept other characters for channel start

### ISSUE THREAD

**Issue by belak** [fluffle/goirc#65]
https://tools.ietf.org/html/rfc1459#section-1.3
https://tools.ietf.org/html/rfc2812#section-1.3

Depending on which RFC you want to believe channels can start with the following characters:
```
RFC1459: '&' or '#'
RFC2812: '&', '#', '+' or '!'
```

**Comment by fluffle** [comment]
Urgh. I knew this day would come. The most-correct thing to do here is implement parsing of IRC 005 messages to extract the CHANTYPES setting, but meh. I *think* the only place this assumption is made is Line.Public(), as you say, and it's reasonably easy to be permissive there. I'll put together a fix.

**Comment by belak** [comment]
Thanks for the quick fix. :)

**Comment by fluffle** [comment]
Caught me at a good time, or it could have taken a while :-)

**Comment by eviltwin** [comment]
Probably a record-breaking turn around for @fluffle - the man deserves a beer :)
