### ISSUE TITLE
Unable to 'go get'

### ISSUE THREAD

**Issue by Tankenstein** [fluffle/goirc#67]
When trying to `go get github.com/fluffle/goirc/client`, it fails and reports the following:
```
# github.com/fluffle/goirc/client
../../fluffle/goirc/client/connection.go:303: undefined: tls.DialWithDialer
```

**Comment by mvdan** [comment]
DialWithDialer was added in 1.3: https://golang.org/doc/go1.3

Update your Go version.

**Comment by Tankenstein** [comment]
Thank you! my bad.
