### ISSUE TITLE
Support IRCv3 capability negotiation during registration.

### ISSUE THREAD

**Issue by fluffle** [fluffle/goirc#77]
http://ircv3.net/specs/core/capability-negotiation-3.1.html
http://ircv3.net/specs/core/capability-negotiation-3.2.html

TL;DR: We need to send a CAP LS before USER and NICK. Not too sure of a final design yet, but one easy way to do it could be to add a []string of capabilities to try and request if the server supports them to the Config struct.

CAP tls and STARTTLS would require different handling, I'll file a different issue for that.

**Comment by wjh** [comment]
I believe this was merged in #76? Perhaps the issue should be closed :)

(wondering if I can contribute)

**Comment by fluffle** [comment]
#76 added tag parsing and the ability to send CAP LS, but there's not yet any code that tries to do IRCv3 CAP negotiation before registration and provide the details of any available capabilities to the user. If you want to send me pull requests I'm happy to review and potentially merge them. The chances of me getting to this soon are reasonably slim, sorry!

**Comment by wjh** [comment]
I'll see if I can find time to take a look at it, though I'm not so sure. No worries either way, been using goirc in some coursework of mine and it's been very useful! Thanks :)

**Comment by ostafen** [comment]
Hi, all! I'm working on this feature. I'll try to provide a PR soon.

**Comment by ostafen** [comment]
I think this could be closed (?)

**Comment by fluffle** [comment]
Agreed and thanks again for your work :-D

**Comment by fluffle** [comment]
Hey there, if you're willing to send me more PRs I won't say no! Sorry for the radio silence, my wife got COVID so I had additional childcare duties, then I got COVID from her and didn't touch a computer for a week or so. All better now though.
