### ISSUE TITLE
question only.

### ISSUE THREAD

**Issue by ChrisFernandez** [fluffle/goirc#80]
Hello, what will be the best practices to monitor for channel commands like !time or whatever new funtions I will like to add to a irc client/bot etc? basically best way to use your framework to monitor private chat and channel chat for bot commands.

Thanks.

**Comment by fluffle** [comment]
I am not sure about the "best" way, but you can have a look at e.g. sp0rkle's commandset:

https://github.com/fluffle/sp0rkle/blob/master/bot/commandset.go

or @StalkR's goircbot handler:

https://github.com/StalkR/goircbot/blob/master/bot/handler.go

Anything that works for you :-)
