### ISSUE TITLE
TestPing is unstable...

### ISSUE THREAD

**Issue by Egojard** [fluffle/goirc#88]
...for the reason you expected yourself according to your comments, the 49-51ms window to check for your ping is too tight.

```
go test github.com/fluffle/...
ok      github.com/fluffle/goevent/event        0.578s
?       github.com/fluffle/goirc        [no test files]
--- FAIL: TestPing (0.21s)
        connection_test.go:426: Line not output after another 2ms.
        connection_test.go:440: Line output after ping stopped.
FAIL
FAIL    github.com/fluffle/goirc/client 0.313s
?       github.com/fluffle/goirc/logging        [no test files]
?       github.com/fluffle/goirc/logging/glog   [no test files]
ok      github.com/fluffle/goirc/state  0.025s
```

So I'm creating the issue as detailed in the comments (connection_test.go l.422)

**Comment by fluffle** [comment]
Where are you running these tests, out of interest? I mean -- they even pass on the free Travis CI service, which has to be a pretty contended platform. Can you experiment with varying the size of the window? I'd be interested to know how much additional time you need.

**Comment by Egojard** [comment]
They seem to fail rather frequently on our build server (Windows 7, 12GB RAM, building amd64 target) though I can reproduce it occasionally on my own machine (windows 10, i7-4790, 16GB RAM) too, maybe one out of ten runs.

Actually, I am suspecting some strange things happen in go's own _time_ library, since I had another of your tests failing, (TestLineCopy,  line_test.go l.42) where you create a line, duplicate it, reset its time marker to time.Now()...  and the duplicate would still get the same time value as the original (which you test for, expecting a different value).

**Comment by Egojard** [comment]
I'll try to experiment a bit further on the error margins required for the test to pass consistently in our environment, but that may take a few days.

**Comment by fluffle** [comment]
Windows, eh? That's not something I've tested on. Perhaps windows time measuring resolution is coarser?

A bit of quick googling turned up:

https://github.com/golang/go/issues/11313
https://github.com/golang/go/issues/8687
https://groups.google.com/forum/#!topic/golang-nuts/7_ybkVpcdiQ
https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

And, most importantly: https://golang.org/doc/go1.6

>  On Windows, Go programs in Go 1.5 and earlier forced the global Windows timer resolution to 1ms at startup by calling timeBeginPeriod(1). Go no longer needs this for good scheduler performance, and changing the global timer resolution caused problems on some systems, so the call has been removed. 

It looks like 15.6ms is the default timer res for windows, so I can relatively easily add a runtime.GOOS check in the test...

**Comment by fluffle** [comment]
OK, so the "fixes" might be premature, but I am optimistic. Let me know if it still fails for you :-)

**Comment by Egojard** [comment]
Thanks for checking this, I'll test it this week.

**Comment by Egojard** [comment]
Sorry, it took me a while to come back to this, bit I just wanted to confirm it does fix the issue. 

You probably should also fix LineCopy which suffers from a related issue : you copy a Line, edit its value, and expect them to be different from the source, but both calls to time.Now() return the same value on windows (I just replaced the second call to time.Now by a manual edition to get the test to pass, but probably not worth a PR).
