### ISSUE TITLE
TLS issues not detected at connection time

### ISSUE THREAD

**Issue by shammash** [fluffle/goirc#89]
Hi Alex,

I am playing with goirc/client. I have noticed that the Connect() method of Conn{} does not return an error upon TLS issues because the handshake happens only after the first read/write.

Could you please consider performing the handshake at connection time, so SSL issues are detected straight away?

This should be enough:

        if conn.cfg.SSL {
                logging.Info("irc.Connect(): Performing SSL handshake.")
                tls_conn := tls.Client(conn.sock, conn.cfg.SSLConfig)
                if err := tls_conn.Handshake(); err != nil {
                        return err
                }
                conn.sock = tls_conn
        }

Thank you,

Luca

**Comment by fluffle** [comment]
Sure, sorry about that!
