### ISSUE TITLE
Can I handle event RECONNECT?

### ISSUE THREAD

**Issue by mitnk** [fluffle/goirc#91]
I wrote a bot with goirc, and in the `CONNECTED` event, it joins a couple of rooms. But sometime the connection to irc server got break, and goirc will reconnect it, but cannot receive messages from these rooms anymore.

How could I catch and handle the `RECONNECTED` (if any) event, so that the bot can rejoin the rooms and receive messages?

Thanks!

**Comment by fluffle** [comment]
I'm a bit confused. If you send JOIN messages in your CONNECTED handler, those join messages should be sent on each reconnect, and your client should rejoin the same channels each time.

Do you have links to code, and debug logs?

**Comment by mitnk** [comment]
oh, thanks for the explanations! It helps a lot! The code was just like the demo code in `client.go`. I didn't do anything on reconnect. I was not sure why I think it reconnected that time. I will have a double check next time!
